/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CctvRouteImport } from './routes/cctv'
import { Route as CommandRouteImport } from './routes/command'
import { Route as EvacuationRouteImport } from './routes/evacuation'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as MapRouteImport } from './routes/map'
import { Route as MissingPersonRouteImport } from './routes/missing-person'
import { Route as RoadsRouteImport } from './routes/roads'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as SosRouteImport } from './routes/sos'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CctvRoute = CctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const EvacuationRoute = EvacuationRouteImport.update({
  id: '/evacuation',
  path: '/evacuation',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MissingPersonRoute = MissingPersonRouteImport.update({
  id: '/missing-person',
  path: '/missing-person',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadsRoute = RoadsRouteImport.update({
  id: '/roads',
  path: '/roads',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/cctv': typeof CctvRoute
  '/command': typeof CommandRoute
  '/evacuation': typeof EvacuationRoute
  '/facilities': typeof FacilitiesRoute
  '/family': typeof FamilyRoute
  '/incidents': typeof IncidentsRoute
  '/map': typeof MapRoute
  '/missing-person': typeof MissingPersonRoute
  '/roads': typeof RoadsRoute
  '/routes': typeof RoutesRoute
  '/sos': typeof SosRoute
  '/vehicles': typeof VehiclesRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/cctv': typeof CctvRoute
  '/command': typeof CommandRoute
  '/evacuation': typeof EvacuationRoute
  '/facilities': typeof FacilitiesRoute
  '/family': typeof FamilyRoute
  '/incidents': typeof IncidentsRoute
  '/map': typeof MapRoute
  '/missing-person': typeof MissingPersonRoute
  '/roads': typeof RoadsRoute
  '/routes': typeof RoutesRoute
  '/sos': typeof SosRoute
  '/vehicles': typeof VehiclesRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/cctv': typeof CctvRoute
  '/command': typeof CommandRoute
  '/evacuation': typeof EvacuationRoute
  '/facilities': typeof FacilitiesRoute
  '/family': typeof FamilyRoute
  '/incidents': typeof IncidentsRoute
  '/map': typeof MapRoute
  '/missing-person': typeof MissingPersonRoute
  '/roads': typeof RoadsRoute
  '/routes': typeof RoutesRoute
  '/sos': typeof SosRoute
  '/vehicles': typeof VehiclesRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/alerts'
    | '/analytics'
    | '/cctv'
    | '/command'
    | '/evacuation'
    | '/facilities'
    | '/family'
    | '/incidents'
    | '/map'
    | '/missing-person'
    | '/roads'
    | '/routes'
    | '/sos'
    | '/vehicles'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/alerts'
    | '/analytics'
    | '/cctv'
    | '/command'
    | '/evacuation'
    | '/facilities'
    | '/family'
    | '/incidents'
    | '/map'
    | '/missing-person'
    | '/roads'
    | '/routes'
    | '/sos'
    | '/vehicles'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/alerts'
    | '/analytics'
    | '/cctv'
    | '/command'
    | '/evacuation'
    | '/facilities'
    | '/family'
    | '/incidents'
    | '/map'
    | '/missing-person'
    | '/roads'
    | '/routes'
    | '/sos'
    | '/vehicles'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CctvRoute: typeof CctvRoute
  CommandRoute: typeof CommandRoute
  EvacuationRoute: typeof EvacuationRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FamilyRoute: typeof FamilyRoute
  IncidentsRoute: typeof IncidentsRoute
  MapRoute: typeof MapRoute
  MissingPersonRoute: typeof MissingPersonRoute
  RoadsRoute: typeof RoadsRoute
  RoutesRoute: typeof RoutesRoute
  SosRoute: typeof SosRoute
  VehiclesRoute: typeof VehiclesRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cctv': {
      id: '/cctv'
      path: '/cctv'
      fullPath: '/cctv'
      preLoaderRoute: typeof CctvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evacuation': {
      id: '/evacuation'
      path: '/evacuation'
      fullPath: '/evacuation'
      preLoaderRoute: typeof EvacuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missing-person': {
      id: '/missing-person'
      path: '/missing-person'
      fullPath: '/missing-person'
      preLoaderRoute: typeof MissingPersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roads': {
      id: '/roads'
      path: '/roads'
      fullPath: '/roads'
      preLoaderRoute: typeof RoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CctvRoute: CctvRoute,
  CommandRoute: CommandRoute,
  EvacuationRoute: EvacuationRoute,
  FacilitiesRoute: FacilitiesRoute,
  FamilyRoute: FamilyRoute,
  IncidentsRoute: IncidentsRoute,
  MapRoute: MapRoute,
  MissingPersonRoute: MissingPersonRoute,
  RoadsRoute: RoadsRoute,
  RoutesRoute: RoutesRoute,
  SosRoute: SosRoute,
  VehiclesRoute: VehiclesRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
